
version: '3'

services:
      mysql:
          image: mariadb:10.1
          restart: always
          ports:
              - 3306:3306
              - 4567:4567/udp
              - 4567-4568:4567-4568 
              - 4444:4444
          environment:
              MYSQL_ROOT_PASSWORD: "password"
              #MYSQL_INITDB_SKIP_TZINFO=yes
          volumes:
              - /opt/local/etc/mysql.conf.d:/etc/mysql/conf.d
              - /mnt/data:/var/lib/mysql
          command:
              -  "--wsrep-new-cluster" 
              - "--wsrep_node_address=149.165.157.87"
              

      spring:
              image: iarora/spring-boot
              build:
                    context: .
                    dockerfile: DockerfileS
              depends_on:
                            - mysql
              environment:
                      OPENSHIFT_MYSQL_DB_HOST: 149.165.157.87
              ports: 
                            - 8082:8082
              volumes:
                            - /data/spring-boot-app
              deploy:
                      replicas: 3




