version: '3'

services:
        spring:
              build:
                   context: .
                   dockerfile: Dockerfile
              ports:
                   - 8083:8082
              image:
                  iarora/dbservice3_spring-tacc:latest
              volumes:
                   - /data/spring-boot-app
              deploy:
                   replicas: 3

